server:
  port: 8080

spring:
  banner:
    charset: UTF-8
    location: banner.txt
  application:
    name: "@project.name@"
    version: "@project.version@"
    build-id: "@project.ci.buildId@"
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.vault: INFO
  pattern:
    level: "%5p [%X{traceId:-}]"
    correlation: ""
